/**
 * @fileoverview Project Scaffolding and Boilerplate Automation Engine for TriDev Shell
 * @author Schlaffer Benjamin
 * @version 1.0.6
 * @description
 * COMMANDS:
 * scaffold <name> <type> [dest] : Generates custom isolated directory scaffolds with structural code.
 * Supported configurations include: web, api, cs, python, react, cli, blank.
 */

//==============================
//* Module Imports
//==============================
const fs = require('fs');
const path = require('path');
const chalk = require('chalk');
const scaffoldJSON = require('../JSON/scaffold.json');

//==============================
//* Constants & Configuration
//==============================
const TEMPLATES = scaffoldJSON.templates;
const GITIGNORE_CONTENT = scaffoldJSON.defaultGitignore;


//==============================
//* Main Command Handler
//==============================
/**
 * Routing gate verifying parameters, setting up destination environments, and driving generation sub-loops.
 * @param {string[]} args - Dynamic parameter components passed downstream out of active console lines.
 * @param {string} currentDir - The active working directory context path of the shell.
 * @returns {void}
 */
function scaffoldCommand(args, currentDir) {
    const [name, type, destination] = args;

    if (!name || !type) {
        showScaffoldUsage();
        return;
    }

    // Dynamic verification mapping explicitly matching templates or internal handling overrides
    if (!TEMPLATES[type] && type !== 'cs') {
        console.log(chalk.red(`\n❌ Unknown project type: "${type}"`));
        showAvailableTypes();
        return;
    }

    // Determine absolute target parents coordinates
    let parentDir = currentDir;
    if (destination) {
        parentDir = path.resolve(currentDir, destination);

        if (!fs.existsSync(parentDir)) {
            console.log(chalk.yellow(`Target directory "${destination}" does not exist. Creating path...`));
            try {
                fs.mkdirSync(parentDir, { recursive: true });
            } catch (err) {
                console.log(chalk.red(`Error creating target path: ${err.message}`));
                return;
            }
        }
    }

    const projectPath = path.join(parentDir, name);

    if (fs.existsSync(projectPath)) {
        console.log(chalk.red(`\n❌ Error: Directory "${name}" already exists in ${parentDir}\n`));
        return;
    }

    console.log(chalk.blue(`\n🔨 Creating ${type} project: ${name}...`));

    try {
        fs.mkdirSync(projectPath, { recursive: true });
        
        // Populate specific boilerplate structures
        createTemplateFiles(type, projectPath, name);
        
        // Write persistent standard global .gitignore configs
        fs.writeFileSync(path.join(projectPath, '.gitignore'), GITIGNORE_CONTENT);
        
        console.log(chalk.green(`✔ Done! Project folder mounted successfully inside target path.\n`));
    } catch (err) {
        console.log(chalk.red('Error creating project structure: ' + err.message));
    }
}


//==============================
//* Core Generation Helpers
//==============================
/**
 * Synchronous file compiler mapping specific codebase configurations onto targeted drive vectors.
 * @param {string} type - Extension mapping key selected during shell initialization checks.
 * @param {string} projectPath - Target structural anchor output coordinate.
 * @param {string} name - Base raw project identity name.
 * @returns {void}
 */
function createTemplateFiles(type, projectPath, name) {
    const safeName = name.toLowerCase().replace(/\s+/g, '-');

    switch (type.toLowerCase()) {
        case 'web': {
            const html = `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${name}</title>\n  <link rel="stylesheet" href="css/style.css">\n</head>\n<body>\n  <div id="app">\n    <h1>${name}</h1>\n    <p>Generated by TriDev Shell</p>\n  </div>\n  <script src="js/app.js"></script>\n</body>\n</html>`;
            fs.writeFileSync(path.join(projectPath, 'index.html'), html);
            fs.mkdirSync(path.join(projectPath, 'css'), { recursive: true });
            fs.writeFileSync(path.join(projectPath, 'css/style.css'), 'body { font-family: sans-serif; background: #1a1a1a; color: #eee; padding: 40px; text-align: center; }');
            fs.mkdirSync(path.join(projectPath, 'js'), { recursive: true });
            fs.writeFileSync(path.join(projectPath, 'js/app.js'), `console.log("${name} initialized.");`);
            break;
        }

        case 'api': {
            const server = `const express = require('express');\nconst app = express();\n\napp.use(express.json());\n\napp.get('/', (req, res) => res.json({ message: '${name} API Online' }));\n\nconst PORT = 3000;\napp.listen(PORT, () => console.log(\`Server running on http://localhost:\${PORT}\`));`;
            fs.writeFileSync(path.join(projectPath, 'index.js'), server);
            fs.writeFileSync(path.join(projectPath, 'package.json'), JSON.stringify({ 
                name: safeName, 
                version: "1.0.0", 
                main: "index.js", 
                scripts: { "start": "node index.js", "dev": "nodemon index.js" },
                dependencies: { express: "^4.18.2" } 
            }, null, 2));
            fs.mkdirSync(path.join(projectPath, 'routes'), { recursive: true });
            fs.mkdirSync(path.join(projectPath, 'models'), { recursive: true });
            break;
        }

        case 'cs': {
            const program = `using System;\n\nnamespace ${name.replace(/\s+/g, '')}\n{\n    class Program\n    {\n        static void Main(string[] args)\n        {\n            Console.WriteLine("TriDev C# Project: ${name} is running!");\n        }\n    }\n}`;
            const csproj = `<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup>\n    <OutputType>Exe</OutputType>\n    <TargetFramework>net8.0</TargetFramework>\n    <ImplicitUsings>enable</ImplicitUsings>\n    <Nullable>enable</Nullable>\n  </PropertyGroup>\n</Project>`;
            fs.writeFileSync(path.join(projectPath, 'Program.cs'), program);
            fs.writeFileSync(path.join(projectPath, `${safeName}.csproj`), csproj);
            break;
        }

        case 'python':
            fs.writeFileSync(path.join(projectPath, 'main.py'), 'def main():\n    print("Hello from TriDev Python script!")\n\nif __name__ == "__main__":\n    main()');
            fs.writeFileSync(path.join(projectPath, 'requirements.txt'), '# Add your dependencies here (e.g., requests, pandas)');
            fs.writeFileSync(path.join(projectPath, 'README.md'), `# ${name}\n\nRun with \`python main.py\``);
            break;

        case 'react':
            fs.mkdirSync(path.join(projectPath, 'public'), { recursive: true });
            fs.writeFileSync(path.join(projectPath, 'public/index.html'), `<!DOCTYPE html><html><head><title>${name}</title></head><body><div id="root"></div></body></html>`);
            fs.mkdirSync(path.join(projectPath, 'src'), { recursive: true });
            fs.writeFileSync(path.join(projectPath, 'src/App.jsx'), 'import React from "react";\n\nexport default function App() {\n  return <h1>${name} (React)</h1>;\n}');
            fs.writeFileSync(path.join(projectPath, 'src/main.jsx'), 'import React from "react";\nimport ReactDOM from "react-dom/client";\nimport App from "./App";\n\nReactDOM.createRoot(document.getElementById("root")).render(<App />);');
            fs.writeFileSync(path.join(projectPath, 'package.json'), JSON.stringify({ 
                name: safeName, version: "0.0.0", 
                scripts: { "dev": "vite", "build": "vite build" },
                dependencies: { react: "^18.0.0", "react-dom": "^18.0.0" } 
            }, null, 2));
            break;

        case 'cli':
            fs.writeFileSync(path.join(projectPath, 'index.js'), `#!/usr/bin/env node\n\nconsole.log("${name} CLI active.");`);
            fs.writeFileSync(path.join(projectPath, 'package.json'), JSON.stringify({ 
                name: safeName, 
                bin: { [safeName]: "index.js" },
                dependencies: { chalk: "^4.1.2" } 
            }, null, 2));
            fs.mkdirSync(path.join(projectPath, 'src'), { recursive: true });
            break;

        case 'blank':
        default:
            fs.writeFileSync(path.join(projectPath, 'README.md'), `# ${name}\n\nInitialized as a blank project via TriDev Shell.`);
            fs.mkdirSync(path.join(projectPath, 'src'), { recursive: true });
            break;
    }
}


//==============================
//* Action Help Displays
//==============================
/** Prints baseline parameter routing guidelines to console out. */
function showScaffoldUsage() {
    console.log(chalk.red('\nUsage: scaffold <name> <type> [dest]'));
    showAvailableTypes();
}

/** Aggregates structural mapping keys dynamically from loaded configuration profiles. */
function showAvailableTypes() {
    // Collect JSON configuration listings and merge structural extensions
    const typesList = [...Object.keys(TEMPLATES), 'cs'].sort();
    console.log(chalk.gray(`Available types: ${typesList.join(', ')}\n`));
}


//==============================
//* Module Exporter
//==============================
module.exports = { scaffoldCommand, TEMPLATES };